In [1]:
#default_exp vaplot

In [2]:
print("this is the file")

this is the file


In [3]:
#export
from EMO_AI.model_api import *

In [4]:
label2int

{'sadness': 0, 'joy': 1, 'love': 2, 'anger': 3, 'fear': 4, 'surprise': 5}

In [2]:
#export
import numpy as np

In [6]:
label2vector = dict()

In [3]:
#export
# helpful when changing the value of each emotional vector
# e.g., label2vector['anger'] = get_vec(1,2)
# , which will change the vector value of 'anger' to np.array([1,2])
# pay attention to the shape when plotting
# *args allows us to input as many dimension as we want, see examples below
def get_vec(*args):
    return np.array(args).reshape(-1,1)

In [9]:
for ele in [get_vec(-0.5,-0.5), get_vec(1,2,3), get_vec(1,2,5,8,-2)]:
    print(ele, "with shape:", ele.shape, end="\n\n")
    print("all the elements:", end=" ")
    for i in range(len(ele)):
        print("ele[%d]: " % (i), ele[i], end="; ")
    print("")

[[-0.5]
 [-0.5]] with shape: (2, 1)

all the elements: ele[0]:  [-0.5]; ele[1]:  [-0.5]; 
[[1]
 [2]
 [3]] with shape: (3, 1)

all the elements: ele[0]:  [1]; ele[1]:  [2]; ele[2]:  [3]; 
[[ 1]
 [ 2]
 [ 5]
 [ 8]
 [-2]] with shape: (5, 1)

all the elements: ele[0]:  [1]; ele[1]:  [2]; ele[2]:  [5]; ele[3]:  [8]; ele[4]:  [-2]; 


In [12]:
"""
# (not important) how i write label2vector in the first place
# helpful when re-writing the maps tho
from EMO_AI.model_api import label2int
tmp = [1,2]
def p(x,y):
    return x,y
print(p(*tmp))
# hand write the vector values in the list
# following the order of label2int map
label2vector = dict()
emovecs = [[-0.5,-0.5],[0.5,0.5],[0.8,0],[-0.8,0.8],[-0.8,0],[0.8,0.8]]
for ele in emovecs: print(p(*ele))
for key, ele in zip(label2int, emovecs):
    label2vector[key] = np.array(ele).reshape(-1,1)
for key, val in label2vector.items():
    print("key:", key, "array:", val)
"""

(1, 2)
(-0.5, -0.5)
(0.5, 0.5)
(0.8, 0)
(-0.8, 0.8)
(-0.8, 0)
(0.8, 0.8)
key: sadness array: [[-0.5]
 [-0.5]]
key: joy array: [[0.5]
 [0.5]]
key: love array: [[0.8]
 [0. ]]
key: anger array: [[-0.8]
 [ 0.8]]
key: fear array: [[-0.8]
 [ 0. ]]
key: surprise array: [[0.8]
 [0.8]]


In [2]:
#export
label2vector = {'sadness': np.array([[-0.5],
        [-0.5]]),
 'joy': np.array([[0.5],
        [0.5]]),
 'love': np.array([[0.8],
        [0. ]]),
 'anger': np.array([[-0.8],
        [ 0.8]]),
 'fear': np.array([[-0.8],
        [ 0. ]]),
 'surprise': np.array([[0.8],
        [0.8]])}

In [3]:
label2vector

{'sadness': array([[-0.5],
        [-0.5]]),
 'joy': array([[0.5],
        [0.5]]),
 'love': array([[0.8],
        [0. ]]),
 'anger': array([[-0.8],
        [ 0.8]]),
 'fear': array([[-0.8],
        [ 0. ]]),
 'surprise': array([[0.8],
        [0.8]])}

#### check the original map, aka, label2int

In [1]:
from EMO_AI.model_api import label2int

In [2]:
#export
"""if you want to see the original map, just use this"""
def check_label2int(print_it=True):
    if print_it:
        for key in label2int:
            print(key,":",label2int[key])
    return label2int

In [4]:
check_label2int(), check_label2int(False) # this works

sadness : 0
joy : 1
love : 2
anger : 3
fear : 4
surprise : 5


({'sadness': 0, 'joy': 1, 'love': 2, 'anger': 3, 'fear': 4, 'surprise': 5},
 {'sadness': 0, 'joy': 1, 'love': 2, 'anger': 3, 'fear': 4, 'surprise': 5})

In [1]:
from EMO_AI.vaplot import check_label2int
# it works, mofo
check_label2int()

sadness : 0
joy : 1
love : 2
anger : 3
fear : 4
surprise : 5


{'sadness': 0, 'joy': 1, 'love': 2, 'anger': 3, 'fear': 4, 'surprise': 5}

In [1]:
"""works"""
# i've create modules for importing the maps with handy, test here temporarily
from EMO_AI.label_maps import *
label2int, label2vector

({'sadness': 0, 'joy': 1, 'love': 2, 'anger': 3, 'fear': 4, 'surprise': 5},
 {'sadness': array([[-0.5],
         [-0.5]]),
  'joy': array([[0.5],
         [0.5]]),
  'love': array([[0.8],
         [0. ]]),
  'anger': array([[-0.8],
         [ 0.8]]),
  'fear': array([[-0.8],
         [ 0. ]]),
  'surprise': array([[0.8],
         [0.8]])})

In [1]:
"""works"""
# test imports.py as well
from EMO_AI.all import *
model = get_model(pretrained=False)
get_output("let it be", model), label2vector

c:\Users\Kelvin\anaconda3\envs\AI_sheng\lib\site-packages\transformers\models\auto\modeling_auto.py:973: FutureWarning: The class `AutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `AutoModelForCausalLM` for causal language models, `AutoModelForMaskedLM` for masked language models and `AutoModelForSeq2SeqLM` for encoder-decoder models.
  FutureWarning,


('joy',
 {'sadness': array([[-0.5],
         [-0.5]]),
  'joy': array([[0.5],
         [0.5]]),
  'love': array([[0.8],
         [0. ]]),
  'anger': array([[-0.8],
         [ 0.8]]),
  'fear': array([[-0.8],
         [ 0. ]]),
  'surprise': array([[0.8],
         [0.8]])})