## Demo 
    how model.py aka backend works

    remember to run in the right env / check if the packages is installed

In [1]:
from EMO_AI.model_api import *
from EMO_AI.data_process import *

### Low level ones

#### get the pretrained model

In [2]:
# change this
PATH = "C:"+chr(92)+"Users"+chr(92)+"Kelvin"+chr(92)+"Desktop"+chr(92)+"ai_sheng"+chr(92)+"emo_0.pt"
model = get_model(PATH, inference_only=False)

# model's architecture should be print
# because of model.eval() (used in the function)

c:\Users\Kelvin\anaconda3\envs\AI_sheng\lib\site-packages\transformers\models\auto\modeling_auto.py:973: FutureWarning: The class `AutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `AutoModelForCausalLM` for causal language models, `AutoModelForMaskedLM` for masked language models and `AutoModelForSeq2SeqLM` for encoder-decoder models.
  FutureWarning,
c:\Users\Kelvin\anaconda3\envs\AI_sheng\lib\site-packages\transformers\optimization.py:310: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,


#### see if run inference (forward pass) works

In [3]:
# from 01 notebook
t = "Elvis is the king of rock"
# idk what happened
setup_tokenizer()
tokenizer = get_tokenizer()
rep = model(convert_text_to_tensor(t))

In [4]:
# it works !
rep

tensor([[-0.1518,  1.4839, -1.5390,  0.5634,  1.1406, -0.9670]],
       grad_fn=<AddmmBackward0>)

#### let's transform the output from tensor to string
#### aka, print the emotion (string) as well

In [7]:
import torch

In [9]:
# first, change the output to the label
out = torch.argmax(rep, dim=1)
print(out)

# get from the label2int map
from EMO_AI.model_api import label2int

for key in label2int:
    if label2int[key] == out:
        print("Emotion: %s" % key)
        break

tensor([1])
Emotion: joy


In [11]:
def print_emotion(output):
    # output = model.forward(input)
    idx = torch.argmax(output, dim=1)
    from EMO_AI.model_api import label2int
    for key in label2int:
        if label2int[key] == idx:
            print("Emotion: %s" % key)
            break
    return key

print_emotion(rep)

Emotion: joy


'joy'

## High level ones

In [16]:
t

'Elvis is the king of rock'

In [20]:
from EMO_AI.model_api import *
call_model(t, PATH, False)

tensor([[-0.3208,  1.0827, -1.8061,  0.9746,  1.3354, -0.8285]],
       grad_fn=<AddmmBackward0>)

In [ ]:
# output has been parsed
output = call_model(input_string, PATH)
# not written yet
plot_emotion(output)