## VA model !!!

In [1]:
from EMO_AI.all import *

In [2]:
model = get_model(pretrained=False)
model

c:\Users\Kelvin\anaconda3\envs\AI_sheng\lib\site-packages\transformers\models\auto\modeling_auto.py:973: FutureWarning: The class `AutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `AutoModelForCausalLM` for causal language models, `AutoModelForMaskedLM` for masked language models and `AutoModelForSeq2SeqLM` for encoder-decoder models.
  FutureWarning,


EmoModel(
  (base_model): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0): RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,

In [4]:
"""

"""
import numpy as np
F = np.array([[0,0]])
text_A = "Fuck"
F, text_A

(array([[0, 0]]), 'Fuck')

In [8]:
outA1 = get_output(text_A,model,return_tensor=True)
""" F(1)"""
"""label: 6"""
outA1 

tensor([[-0.0390, -0.1461,  0.1041, -0.1185, -0.1062, -0.0074]])

In [14]:
label2vector["love"] # 

array([[0.8],
       [0. ]])

In [15]:
a,b = 0.9, 1

In [17]:
F0

array([[0, 0]])

In [19]:
F0 = F
F1 = a*F0 + (1-a)*label2vector["love"]
F1 = F1[:,1]

In [20]:
F1

array([0.08, 0.  ])

In [21]:
text_B = "The Fuck"
outB = get_output(text_B, model)
outB

'love'

In [30]:
"S"
S = label2vector[outB]
S

array([[0.8],
       [0. ]])

In [26]:
"VA previous"
va_pre = label2vector["love"] * b
va_pre

array([[0.8],
       [0. ]])

In [28]:
F2 = a*F1 + (1-a)*label2vector[outB]
F2 = F2[:,0]

In [29]:
F2

array([0.152, 0.072])

In [31]:
outA2 = get_output("What's your problem", model)
outA2

'love'

In [33]:
"Va new"
label2vector[outA2] * b

array([[0.8],
       [0. ]])

In [ ]:
"VA model input"
F2, S, va_pre
"output: Va new -> Va previous (next epoch)"

### 手抓 -> 寫程式處理(F2, S, Va previous, Va new))
### 訓練

# 找到資料 (SHXT))